String generateTerms() {
  return "Welcome to Grandeur Real Estate App!\n\n"
      "By using this app, you agree to the following terms and conditions:\n\n"
      "- The information provided in this app is for general informational purposes only.\n"
      "- Grandeur Real Estate App does not guarantee the accuracy, completeness, or reliability of any information displayed.\n"
      "- All property listings are subject to availability and may change without notice.\n"
      "- Grandeur Real Estate App is not responsible for any transactions or agreements made between users.\n"
      "- Users are solely responsible for verifying the accuracy of any information before making any decisions.\n"
      "- Grandeur Real Estate App reserves the right to modify or terminate the app at any time without prior notice.\n"
      "- By using this app, you agree to comply with all applicable laws and regulations.\n"
      "- Grandeur Real Estate App may collect and use your personal information as described in our privacy policy.\n"
      "- Use of this app is at your own risk.\n"
      "- The app may include links to third-party websites or services that are not owned or controlled by Grandeur Real Estate App.\n"
      "- Grandeur Real Estate App has no control over and assumes no responsibility for the content, privacy policies, or practices of any third-party websites or services.\n"
      "- You further acknowledge and agree that Grandeur Real Estate App shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such websites or services.\n"
      "- Grandeur Real Estate App strongly advises you to read the terms and conditions and privacy policies of any third-party websites or services that you visit.\n"
      "- Grandeur Real Estate App reserves the right to update or change these terms and conditions at any time without prior notice.\n"
      "- Any new features or tools added to the app shall also be subject to the terms and conditions.\n"
      "- Continued use of the app after any such changes shall constitute your consent to such changes.\n\n"
      "Thank you for choosing Grandeur Real Estate App!";
}
